# Generated by Django 5.0.2 on 2024-09-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_applicant_image_alter_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
