# Generated by Django 5.0.2 on 2024-09-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_applicant_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
