# Generated by Django 5.0.2 on 2024-09-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_applicant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
