# Generated by Django 5.1 on 2025-05-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_applicant_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='district',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='pincode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
